-- Schema is now managed by Alembic migrations (api/migrations/).
-- Run `alembic upgrade head` (or let the API container do it on startup)
-- to apply all migrations to a fresh database.
--
-- This file is kept so the postgres container mounts succeed without error.
-- It intentionally contains no DDL.
